#!/usr/bin/env node

var program = require('commander');
var gitHooks = require('./dist/git-hook-scripts.js');

program
    .version(require('./package.json').version);

program
    .command('check-issue-nr-in-commit-msg')
    .alias('issue-nr')
    .description('Check if commit message has a Issue number marked down')
    .action(gitHooks.checkIssueNrInCommitMsg);

program
    .command('npm-install-after-merge')
    .alias('install')
    .description('Call npm intall if package.json or bower.json has been changed after Merge')
    .action(gitHooks.npmInstallAfterMerge);

program.parse(process.argv);

if (!program.args.length)
    program.help();
